tegra-libraries rework
madisongh/meta-tegra pull request #819
Opened 2021-10-17 15:12 UTC by madisongh

* Replaces the `tegra-libraries` recipe with multiple recipes that install subsets of the libraries/files. The subsets are roughly aligned with the `nvidia-l4t-*` deb packages that NVIDIA provides, but not exactly the same due to build-time dependencies.
* Adjusts other recipes in the layer to use build-time DEPENDS on the specific `tegra-libraries-*` recipes required, letting the build system create the necessary runtime dependencies.

I've done some testing on `demo-image-full` in the demo distro.  Needs some testing on distros that don't use X11, and on `demo-image-weston` to make sure the needed libraries all show up.

2021-10-17 18:36 UTC, ichergui requested changes

2021-10-17 18:36 UTC, ichergui commented on recipes-bsp/tegra-binaries/tegra-libraries-core_32.6.1.bb
> +    tegra/libnvisp_utils.so \
`libnvisp_utils.so` library is not supported for `tegra210`

2021-10-17 18:39 UTC, ichergui commented
I think we need some changes in `tegra-libraries-core` recipe.
Kindly  find the patch attached

[0001-updates-in-tegra-libraries-core.txt](https://github.com/OE4T/meta-tegra/files/7360628/0001-updates-in-tegra-libraries-core.txt)

2021-10-17 21:08 UTC, ichergui commented on recipes-bsp/tegra-binaries/tegra-libraries-camera_32.6.1.bb
> +    tegra/libnvcapture.so \
`libnvcapture.so` library is not supported for `tegra210`

2021-10-17 21:16 UTC, ichergui commented on recipes-bsp/tegra-binaries/tegra-libraries-multimedia-v4l_32.6.1.bb
> +    for f in libv4l2_nvvideocodec.so libv4l2_nvcuvidvideocodec.so; do
`libv4l2_nvcuvidvideocodec.so` library is not supported for `tegra210`
Maybe we have to add condition to check if library exists.
Something like:

```
 do_install() {
     install_libraries
     install -d ${D}${libdir}/libv4l/plugins/ ${D}${libdir}/libv4l/plugins-wrapped/
     for f in libv4l2_nvvideocodec.so libv4l2_nvcuvidvideocodec.so; do
          if [ -e "${DRVROOT}/tegra/$f" ]; then
               install -m 0644 ${DRVROOT}/tegra/$f ${D}${libdir}/libv4l/plugins/
          fi
     done
     install -m 0644 ${DRVROOT}/tegra/libv4l2_nvvidconv.so ${D}${libdir}/libv4l/plugins-wrapped/
 }
```

2021-10-17 21:17 UTC, ichergui commented on recipes-bsp/tegra-binaries/tegra-libraries-multimedia-v4l_32.6.1.bb
> +    tegra/libnvcuvidv4l2.so \
`libnvcuvidv4l2.so` library is not supported for `tegra210`

2021-10-17 21:39 UTC, ichergui commented
I have another patch to update `tegra-libraries-camera` and `tegra-libraries-multimedia-v4l`
Kindly find the patch attached

[0002-updates-in-tegra-libraries-camera-and-multimedia-v4l.txt](https://github.com/OE4T/meta-tegra/files/7360906/0002-updates-in-tegra-libraries-camera-and-multimedia-v4l.txt)

2021-10-17 23:49 UTC, ichergui commented
Tests were done by using machine `jetson-nano-emmc` with the following the images
It looks good to me.
* `demo-image-base`
* `demo-image-egl`
* `demo-image-weston`
* `demo-image-full`

More tests are needed when using other machines (`jetson-tx2`, `jetson-xavier-nx`, `jetson-xavier-agx`, ...)

2021-10-18 13:09 UTC, ichergui approved these changes

2021-10-18 16:24 UTC, kekiefer commented on recipes-bsp/tegra-binaries/tegra-libraries-vulkan_32.6.1.bb
> +REQUIRED_DISTRO_FEATURES = "x11 vulkan"
The vukan-loader recipe has a dependency on x11. Whether this is valid or not is a good question. But for the purposes of these libraries, it is not needed.

2021-10-18 20:02 UTC, kekiefer approved these changes

2021-10-18 20:16 UTC, merged